# Generated by Django 4.2.21 on 2025-06-02 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedarticle',
            options={'verbose_name': 'Сохраненная статья', 'verbose_name_plural': 'Сохраненные статьи'},
        ),
    ]
