# Generated by Django 5.2 on 2025-05-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Пол'),
        ),
    ]
