# Generated by Django 4.2.22 on 2025-06-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_alter_pet_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='features',
            field=models.TextField(blank=True, help_text='Аллергии, хронические заболевания и другие особенности питомца', null=True, verbose_name='Особенности'),
        ),
    ]
