# Generated by Django 5.2 on 2025-05-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='profile/d4.jpg', null=True, upload_to='profile/', verbose_name='avatar'),
        ),
    ]
