# Generated by Django 4.2.21 on 2025-05-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='profile/d5.jpg', null=True, upload_to='profile/', verbose_name='avatar'),
        ),
    ]
