# Generated by Django 4.2.21 on 2025-06-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='profile/d4.jpg', null=True, upload_to='profile/', verbose_name='avatar'),
        ),
    ]
