# Generated by Django 4.2.21 on 2025-06-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='profile/d7.jpg', null=True, upload_to='profile/', verbose_name='avatar'),
        ),
    ]
