# Generated by Django 5.2 on 2025-05-03 13:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('walk', 'Прогулка'), ('vet', 'Ветеринар'), ('grooming', 'Груминг'), ('vaccine', 'Прививка'), ('pill', 'Приём таблетки'), ('birthday', 'День рождения')], max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='pets.pet')),
            ],
        ),
        migrations.CreateModel(
            name='ReminderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remind_at', models.TimeField(blank=True, null=True)),
                ('repeat', models.BooleanField(default=False)),
                ('repeat_days', models.JSONField(blank=True, default=list)),
                ('repeat_every', models.PositiveIntegerField(default=1)),
                ('remind_date', models.DateField(blank=True, null=True)),
                ('last_reminded', models.DateField(blank=True, null=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reminder', to='calendarapp.event')),
                ('pet', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pets.pet')),
            ],
        ),
    ]
