# Generated by Django 4.2.21 on 2025-05-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_yearly',
            field=models.BooleanField(default=False, verbose_name='Ежегодное событие'),
        ),
    ]
