# Generated by Django 4.2.21 on 2025-05-27 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0002_event_is_yearly'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='done_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
