# Generated by Django 4.2.21 on 2025-06-03 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0003_event_done_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date', 'time']},
        ),
        migrations.AddField(
            model_name='event',
            name='original_yearly_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yearly_instances', to='calendarapp.event', verbose_name='Оригинальное ежегодное событие'),
        ),
    ]
