# Generated by Django 4.2.21 on 2025-06-03 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0004_alter_event_options_event_original_yearly_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
        migrations.RemoveField(
            model_name='event',
            name='original_yearly_event',
        ),
    ]
