# Generated by Django 4.2.21 on 2025-06-03 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0005_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='original_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_events', to='calendarapp.event'),
        ),
    ]
