# Generated by Django 4.2.21 on 2025-06-03 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_alter_pet_gender'),
        ('calendarapp', '0006_event_original_event'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('pet', 'title', 'date')},
        ),
    ]
