# Generated by Django 4.2.22 on 2025-06-08 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0007_alter_event_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_event_passed',
            field=models.BooleanField(default=False, verbose_name='Событие прошло'),
        ),
    ]
