# Generated by Django 5.2 on 2025-05-03 13:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='training_videos/')),
                ('text_content', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PetLessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'Проходит сейчас'), ('completed', 'Завершено')], default='in_progress', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.lesson')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='pets.pet')),
            ],
            options={
                'unique_together': {('pet', 'lesson')},
            },
        ),
    ]
