# Generated by Django 4.2.21 on 2025-05-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='lesson_covers/'),
        ),
    ]
